#!/bin/bash

WHICHPD="Pd-0.48-1"

/Applications/$WHICHPD.app/Contents/Resources/bin/pd -nogui -stderr -audiodev 2 main_piano.pd & 

sleep 2

/Applications/$WHICHPD.app/Contents/Resources/bin/pd -nogui -stderr -audiodev 2 main.pd & 

sleep 1

/Applications/$WHICHPD-i386.app/Contents/Resources/bin/pd -nogui -noaudio -send ";reader 1" -open main_gem.pd

